### ISSUE TITLE
Is it possible to get an example of the inputs? 

### ISSUE THREAD

**Issue by arjunkalburgi** [DISCOSUMO/query-based_summarization#1]
I'd like to modify your algorithm slightly so I can use it in my conversational agent. I'd be really nice to see what the file that it reads looks like. 

Or even better, what the termvectors and queryvector parameters look like when passed to the MMR function. 

Thanks!

**Comment by suzanv** [comment]
Hi, thanks for your comment! I added example input (small query file and directory with threads)
